### ISSUE TITLE
Ethinicity doesn't seem to be available in MIMIC-IV, Did you mean by Race? What is the supported MIMIC-IV version?

### ISSUE THREAD

**Issue by FrozenWolf-Cyber** [nyuad-cai/MedFuse#18]
I seem to notice ethnicity being used in code, which is missing in MIMIC IV, and race seems to be the closest column. I also see a 'core' module being used, which is not present in MIMIC-IV 2.2. So the current extraction code supports which version of MIMIC IV?

**Comment by ShazaElsharief** [comment]
This extraction code was developed for MIMIC-IV V1.0 (2021). This version does have the core, hosp, and icu modules present, which is why you see the ‘core’ module used in code. The ethnicity column also does exist in V1.0 (but may not in the more recent version you are referring to). In specific, it is found in the ‘admissions’ table in the core module. Please refer to the following for more detail:  

Alistair Johnson, Lucas Bulgarelli, Tom Pollard, Steven Horng, Leo Anthony Celi, and Roger Mark. “mimic-iv” (version 1.0). physionet (2021). https://doi.org/10.13026/s6n6-xd98., 2021.
